### PR TITLE
Renamed ../worker/master.go to ../worker/masterClient.go

### PR DESCRIPTION
**Pull request by dileepchidurala**
Renamed the master in ./worker to masterClient.go. No other changes required as the file name is not used in any other part of the code.

### CODE REVIEW

**Review by naturetime10 — CHANGES_REQUESTED** [review]
In Go, we use lower case for file name! And we should rename the struct to MasterClient!

**Comment by naturetime10** [comment]
It seems that this file is being added instead of renamed.

**Comment by dileepchidurala** [comment]
I believe renaming a file git will consider the old file(../worker/master.go) is deleted and created a new file( ../worker/masterClient.go). doesn't it?

**Comment by naturetime10** [comment]
@dileepchidurala It seems that you have to check in the deletion also.

**Comment by dileepchidurala** [comment]
okay, my bad, but I already made another commit over it, Can I continue or need to go back and make sure that deletion logs in the commit?

**Comment by naturetime10** [comment]
@dileepchidurala You probably need one more commit to remove the file you deleted. What's the output of `git status`?

**Comment by dileepchidurala** [comment]
@byliuyang After my last commit which is one head of this PR commit.
 deleted:    worker/masterClient.go
 renamed:    worker/master.go -> worker/master_client.go
 modified:   worker/worker.go
I will just create a new branch from master and make sure deletion gets to commit. Is that okay to close this PR ?

**Comment by dileepchidurala** [comment]
Closing this PR as it has missing deleted file in the commit.

**Pull request closed without merging**
